function Pierresuite2pFolderStatusCellROITesting = importManualCellRoiValidationSpreadsheetFile(filename, dataLines)
%importManualCellRoiValidationSpreadsheetFile Import data from a text file
%  PIERRESUITE2PFOLDERSTATUSCELLROITESTING = IMPORTFILE(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as a table.
%
%  PIERRESUITE2PFOLDERSTATUSCELLROITESTING = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Pierresuite2pFolderStatusCellROITesting = importfile("/Users/pho/repo/phoCrossDayAlignment/data/Pierre suite2p Folder Status - CellROI Testing.csv", [5, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Dec-2020 15:48:22

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 18);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "uniqueCompListIndex", "roiName", "compID", "session0", "session1", "session2", "isSelected", "isExcluded", "isBad", "QualityOfTuningoutOf10", "TunedFreqs", "TunedAmps", "Notes", "QualityOfTuningWithZeros", "Var16", "Var17", "Var18"];
opts.SelectedVariableNames = ["uniqueCompListIndex", "roiName", "compID", "session0", "session1", "session2", "isSelected", "isExcluded", "isBad", "QualityOfTuningoutOf10", "TunedFreqs", "TunedAmps", "Notes", "QualityOfTuningWithZeros"];
opts.VariableTypes = ["char", "double", "char", "double", "double", "double", "double", "double", "double", "double", "double", "char", "char", "char", "double", "char", "char", "char"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "roiName", "TunedFreqs", "TunedAmps", "Notes", "Var16", "Var17", "Var18"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "roiName", "TunedFreqs", "TunedAmps", "Notes", "Var16", "Var17", "Var18"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["uniqueCompListIndex", "compID", "session0", "session1", "session2", "isSelected", "isExcluded", "isBad", "QualityOfTuningoutOf10", "QualityOfTuningWithZeros"], "FillValue", 0);

% Import the data
Pierresuite2pFolderStatusCellROITesting = readtable(filename, opts);

end